#!C:\Users\CRT402\Desktop\会社\21_研修\dmm\lesson23_4_product.recommend\ダウンロード用\product_recommend\env\Scripts\python.exe

import docx2txt

if __name__ == '__main__':
    import sys
    args = docx2txt.process_args()
    text = docx2txt.process(args.docx, args.img_dir)
    output = getattr(sys.stdout, 'buffer', sys.stdout)
    output.write(text.encode('utf-8'))
